In [62]:
import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# 1. Read data txt

## Read feature

In [67]:
data_feature = []
data_feature = pd.read_csv("https://raw.githubusercontent.com/DangCao1999/ML-Study/master/BaiHoc/Naive%20Bayes/MyDemo/DataBt1.txt",  sep=" ", header=None)
print(data_feature.head())

   0  1  2
0  1  1  1
1  1  2  1
2  1  4  1
3  2  2  1
4  2  3  1


## Read label

In [68]:
data_label = []
data_label = pd.read_csv("https://raw.githubusercontent.com/DangCao1999/ML-Study/master/BaiHoc/Naive%20Bayes/MyDemo/LabelBt1.txt", sep=" ", header=None)

# 2. Sparse matrix

In [69]:
nwords = 5
nemails = 10
rows = data_feature[0] -1 
cols = data_feature[1] -1 
data = data_feature[2]
coo_data = coo_matrix((data, (rows, cols)), shape=(nemails, nwords)).toarray()

In [70]:
print(coo_data)

[[1 1 0 1 0]
 [0 1 1 0 0]
 [1 0 1 0 1]
 [1 1 1 1 0]
 [0 1 0 1 0]
 [0 0 0 1 1]
 [0 1 0 0 0]
 [1 1 0 1 0]
 [0 0 1 1 1]
 [1 0 1 0 1]]


# 3. Train - Test

In [93]:
train_feature, test_feature, train_label, test_label = train_test_split(coo_data, data_label, test_size = 0.3, random_state=1)

In [94]:
train_label = train_label.values.reshape(len(train_label)) # fix for warning shape(n_samples,)

In [95]:
MNB = MultinomialNB()
MNB.fit(train_feature, train_label)

MultinomialNB()

# 4. Predict - Evulation Accuracy

In [96]:
predict_label = MNB.predict(test_feature)
print(predict_label)

['N' 'N' 'S']


In [97]:
print('Training size = %d, accuracy = %.2f%%' % \
      (coo_data.shape[0], accuracy_score(test_label, predict_label)*100))

Training size = 10, accuracy = 33.33%
